name = "outerfaith/moonstone"
version = "0.1.0"
description = "An open-source server implementation for Minecraft 26.2"
authors = ["Outerfaith"]
repository = "https://github.com/outerfaith/moonstone"
license = "Apache-2.0"

[dependencies]
result = { name = "word30210/luau_result", version = "^0.1.3" }

[target]
environment = "luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
