plugins {
    kotlin("jvm") version "2.3.20"
    id("org.spongepowered.gradle.vanilla") version "0.3.2"
}

kotlin {
    jvmToolchain(25)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0-rc01")
}

minecraft {
    version("26.1.2")
    runs {
        server("codegenServer") {
            mainClass("dev.outerfaith.moonstone.codegen.MainKt")
            args(rootProject.rootDir.resolve("src/autogenerated").absolutePath)
        }
    }
    platform(org.spongepowered.gradle.vanilla.repository.MinecraftPlatform.SERVER)
}
